const newProducts = [
    {
        productId:1,
      productDetailsLink: "product-details.html",
      primaryImage: "assets/img/product/product1.png",
      secondaryImage: "assets/img/product/product2.png",
      badgeText: "Sale",
      subtitle: "Jacket, Women",
      title: "Oversize Cotton Dress",
      currentPrice: "$110",
      oldPrice: "$78",
      rating: 3,
      addToCartLink: "cart.html",
      wishlistLink: "wishlist.html",
      quickViewLink: "javascript:void(0)",
      productAvailability: "In Stock"
    },
    {
        productId:2,
      productDetailsLink: "product-details2.html",
      primaryImage: "assets/img/product/product3.png",
      secondaryImage: "assets/img/product/product4.png",
      badgeText: "New",
      subtitle: "Shirt, Men",
      title: "Slim Fit Plaid Shirt",
      currentPrice: "$45",
      oldPrice: "$55",
      rating: 4,
      addToCartLink: "cart.html",
      wishlistLink: "wishlist.html",
      quickViewLink: "javascript:void(0)",
      productAvailability: "In Stock"
    },
    {
        productId:3,
      productDetailsLink: "product-details3.html",
      primaryImage: "assets/img/product/product5.png",
      secondaryImage: "assets/img/product/product6.png",
      badgeText: "Sale",
      subtitle: "Jeans, Men",
      title: "Classic Blue Jeans",
      currentPrice: "$60",
      oldPrice: "$75",
      rating: 5,
      addToCartLink: "cart.html",
      wishlistLink: "wishlist.html",
      quickViewLink: "javascript:void(0)",
      productAvailability: "In Stock"
    },
    {
        productId:4,
      productDetailsLink: "product-details4.html",
      primaryImage: "assets/img/product/product7.png",
      secondaryImage: "assets/img/product/product8.png",
      badgeText: "Sale",
      subtitle: "Dress, Women",
      title: "Floral Print Maxi Dress",
      currentPrice: "$90",
      oldPrice: "$120",
      rating: 4.5,
      addToCartLink: "cart.html",
      wishlistLink: "wishlist.html",
      quickViewLink: "javascript:void(0)",
      productAvailability: "In Stock"
    },
    {
        productId:5,
      productDetailsLink: "product-details5.html",
      primaryImage: "assets/img/product/product9.png",
      secondaryImage: "assets/img/product/product10.png",
      badgeText: "New",
      subtitle: "Sneakers, Unisex",
      title: "High Top Canvas Sneakers",
      currentPrice: "$35",
      oldPrice: "$40",
      rating: 4,
      addToCartLink: "cart.html",
      wishlistLink: "wishlist.html",
      quickViewLink: "javascript:void(0)",
      productAvailability: "In Stock"
    },
  ];

  export default newProducts;
